import LocalizedStrings from 'react-native-localization'

export const strings = new LocalizedStrings({
  en: {
    cryptoApp: 'CryptoApp',
    signInMessage: 'Welcome to',
    headerMessage: '👋 Hello',
    googleSignIn: 'Sign in with Google',
    search: 'Search',
    favorites: 'Favorites',
    signOut: 'Sign out',
    noDataFound: 'No data found for these filters',
    close: 'Close',
    details: 'Details',
    detailsName: 'Name',
    detailsSymbol: 'Symbol',
    detailsRank: 'Rank',
    detailsPrice: 'Price',
    detailsVolume: 'Volume 24h',
    detailsMarketCap: 'Market Cap',
    detailsCirculatingSupply: 'Circulating Supply',
    detailsTotalSupply: 'Total Supply',
    detailsMaxSupply: 'Max Supply',
    detailsLastUpdated: 'Last Updated',
    error: 'An error occurred. Please try again later.',
  },
  es: {
    cryptoApp: 'CryptoApp',
    signInMessage: '¡Bienvenido a',
    headerMessage: '👋 ¡Hola',
    googleSignIn: 'Iniciar sesión con Google',
    search: 'Buscar',
    favorites: 'Favoritos',
    signOut: 'Cerrar sesión',
    noDataFound: 'No se encontraron datos para estos filtros',
    close: 'Cerrar',
    details: 'Detalles',
    detailsName: 'Nombre',
    detailsSymbol: 'Símbolo',
    detailsRank: 'Rango',
    detailsPrice: 'Precio',
    detailsVolume: 'Volumen 24h',
    detailsMarketCap: 'Capitalización de mercado',
    detailsCirculatingSupply: 'Suministro circulante',
    detailsTotalSupply: 'Suministro total',
    detailsMaxSupply: 'Suministro máximo',
    detailsLastUpdated: 'Última actualización',
    error: 'Se produjo un error. Por favor, inténtelo de nuevo más tarde.',
  },
})
